name: Ricerca lavoro Ticino

on:
  workflow_dispatch:

jobs:

  ricerca:

    runs-on: ubuntu-latest

    steps:

    - name: Scarica codice
      uses: actions/checkout@v4


    - name: Installa Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Installa librerie
      run: |
        pip install -r requirements.txt


    - name: Avvia agente
      run: |
        python test.py
